spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
    include:

server:
  port: 8080

logging:
  level:
    root: INFO

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
      presigned-url:
        expiration-minutes: 10 # presigned URL 만료 시간 (분 단위)
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN}

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com