spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false         #성능 & 보안 이유로 비활성화
    properties:
      hibernate:
        format_sql: false

springdoc:
  swagger-ui:
    enabled: false